version: '3.9'

services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  api:
    build:
      target: development
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"

  worker:
    build:
      target: development
    command: npm run start:worker
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development